### ISSUE TITLE
Windows build not update

### ISSUE THREAD

**Issue by virgonia** [FirebirdSQL/snapshots#1]
WIndows build not update on snapshot.
https://github.com/FirebirdSQL/snapshots/releases/tag/snapshot-master
![Screenshot 2022-11-01 080937](https://user-images.githubusercontent.com/30924531/199137148-d9abd67e-bbd1-47c5-8715-a33745686b94.jpg)

**Comment by asfernandes** [comment]
Should be updated tomorrow.

**Comment by virgonia** [comment]
![image](https://user-images.githubusercontent.com/30924531/200098344-c5db097e-7130-4505-b4a0-5c7406a54bb8.png)

**Comment by asfernandes** [comment]
Updated now.
